// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package filetypechecker.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import filetypechecker.impl.FileTypeChecker;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetFileType extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __inputFile;
	private system.proxies.FileDocument inputFile;

	public GetFileType(IContext context, IMendixObject inputFile)
	{
		super(context);
		this.__inputFile = inputFile;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.inputFile = __inputFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __inputFile);

		// BEGIN USER CODE
		IContext context = this.context();

		if (inputFile != null && inputFile.getHasContents(context)) {
			FileTypeChecker fileTypeChecker = new FileTypeChecker();
			return fileTypeChecker.getFileType(__inputFile, context);
		}

		else {
			throw new NullPointerException("Empty input file in FileTypeChecker.");
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetFileType";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
