// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fileidentifier.actions;

import java.io.InputStream;
import org.apache.tika.Tika;
import org.apache.tika.io.TikaInputStream;
import org.apache.tika.metadata.Metadata;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns the file type (MIME type) of the input file.
 */
public class GetFileType extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __InputFile;
	private system.proxies.FileDocument InputFile;

	public GetFileType(IContext context, IMendixObject InputFile)
	{
		super(context);
		this.__InputFile = InputFile;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.InputFile = __InputFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __InputFile);

		// BEGIN USER CODE

		if (InputFile != null && InputFile.getHasContents()) {

			InputStream inputStream = null;
			TikaInputStream tikaStream = null;
			String mimeType;

			try {
				Tika tika = new Tika();
				inputStream = Core.getFileDocumentContent(this.context(), __InputFile);
				tikaStream = TikaInputStream.get(inputStream);
				Metadata metadata = new Metadata();
				metadata.set(Metadata.RESOURCE_NAME_KEY, InputFile.getName());
				mimeType = tika.detect(tikaStream, metadata);

			} catch (Throwable t) {
				return "Unable to identify file.";

			} finally {
				if (inputStream != null) {
					inputStream.close();
				}
				if (tikaStream != null) {
					tikaStream.close();
				}
			}
			return mimeType.toString();

		}
		else {
			return "No file inserted.";
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetFileType";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
