// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package fileidentifier.actions;

import java.io.InputStream;
import java.io.File;
import org.apache.tika.Tika;
import org.apache.tika.config.TikaConfig;
import org.apache.tika.detect.DefaultDetector;
import org.apache.tika.detect.Detector;
import org.apache.tika.io.TikaInputStream;
import org.apache.tika.metadata.Metadata;
import org.apache.tika.mime.MediaType;
import org.apache.tika.parser.Parser;
import org.apache.tika.detect.MagicDetector;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Returns the MIME-type of the input file. For a complete list of MIME-types go to https://www.freeformatter.com/mime-types-list.html. 
 */
public class GetMimeType extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __InputFile;
	private system.proxies.FileDocument InputFile;

	public GetMimeType(IContext context, IMendixObject InputFile)
	{
		super(context);
		this.__InputFile = InputFile;
	}

	@Override
	public java.lang.String executeAction() throws Exception
	{
		this.InputFile = __InputFile == null ? null : system.proxies.FileDocument.initialize(getContext(), __InputFile);

		// BEGIN USER CODE
		InputStream inputStream = Core.getFileDocumentContent(this.context(), __InputFile);	
		Detector detector = new DefaultDetector();
		MediaType mimetype = detector.detect(TikaInputStream.get(inputStream), new Metadata());
		return mimetype.toString();
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetMimeType";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
